// <auto-generated />
using System;
using IPO.FeeService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IPO.FeeService.Data.Migrations
{
    [DbContext(typeof(FeeDbContext))]
    [Migration("20251208111444_AddProductNumberColumnToProductsTable")]
    partial class AddProductNumberColumnToProductsTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IPO.FeeService.Models.Data.Fee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EffectiveFrom")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EffectiveTo")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("PriceExVat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("Rule")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasDefaultValue("No Rule Effective Fee = 1");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("Fees");
                });

            modelBuilder.Entity("IPO.FeeService.Models.Data.FeesDataSeedingHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("FeesDataSeedingHistories");
                });

            modelBuilder.Entity("IPO.FeeService.Models.Data.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Description")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int?>("ProductNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("IPO.FeeService.Models.Data.ProductServiceRequestType", b =>
                {
                    b.Property<int>("ProductsId")
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    b.Property<int>("ServiceRequestTypesId")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<int>("ProductSequence")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("ProductsId", "ServiceRequestTypesId");

                    b.HasIndex("ServiceRequestTypesId");

                    b.ToTable("ProductServiceRequestType", (string)null);
                });

            modelBuilder.Entity("IPO.FeeService.Models.Data.QuantityRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EffectiveFrom")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EffectiveTo")
                        .HasColumnType("datetime2");

                    b.Property<string>("Rule")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.ToTable("QuantityRules");
                });

            modelBuilder.Entity("IPO.FeeService.Models.Data.ServiceRequestType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("E5AccountNumber")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("nvarchar(35)");

                    b.HasKey("Id");

                    b.ToTable("ServiceRequestTypes");
                });

            modelBuilder.Entity("IPO.FeeService.Models.Data.TaxCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Description")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<DateTime>("EffectiveFrom")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EffectiveTo")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Rate")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.ToTable("TaxCodes");
                });

            modelBuilder.Entity("ProductQuantityRule", b =>
                {
                    b.Property<int>("ProductsId")
                        .HasColumnType("int");

                    b.Property<int>("QuantityRulesId")
                        .HasColumnType("int");

                    b.HasKey("ProductsId", "QuantityRulesId");

                    b.HasIndex("QuantityRulesId");

                    b.ToTable("ProductQuantityRule");
                });

            modelBuilder.Entity("ProductTaxCode", b =>
                {
                    b.Property<int>("ProductsId")
                        .HasColumnType("int");

                    b.Property<int>("TaxCodesId")
                        .HasColumnType("int");

                    b.HasKey("ProductsId", "TaxCodesId");

                    b.HasIndex("TaxCodesId");

                    b.ToTable("ProductTaxCode");
                });

            modelBuilder.Entity("IPO.FeeService.Models.Data.Fee", b =>
                {
                    b.HasOne("IPO.FeeService.Models.Data.Product", "Product")
                        .WithMany("Fees")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("IPO.FeeService.Models.Data.ProductServiceRequestType", b =>
                {
                    b.HasOne("IPO.FeeService.Models.Data.Product", "Product")
                        .WithMany("ProductServiceRequestTypes")
                        .HasForeignKey("ProductsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IPO.FeeService.Models.Data.ServiceRequestType", "ServiceRequestType")
                        .WithMany("ProductServiceRequestTypes")
                        .HasForeignKey("ServiceRequestTypesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("ServiceRequestType");
                });

            modelBuilder.Entity("ProductQuantityRule", b =>
                {
                    b.HasOne("IPO.FeeService.Models.Data.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IPO.FeeService.Models.Data.QuantityRule", null)
                        .WithMany()
                        .HasForeignKey("QuantityRulesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProductTaxCode", b =>
                {
                    b.HasOne("IPO.FeeService.Models.Data.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IPO.FeeService.Models.Data.TaxCode", null)
                        .WithMany()
                        .HasForeignKey("TaxCodesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("IPO.FeeService.Models.Data.Product", b =>
                {
                    b.Navigation("Fees");

                    b.Navigation("ProductServiceRequestTypes");
                });

            modelBuilder.Entity("IPO.FeeService.Models.Data.ServiceRequestType", b =>
                {
                    b.Navigation("ProductServiceRequestTypes");
                });
#pragma warning restore 612, 618
        }
    }
}
